### ISSUE TITLE
Editing automations from the UI

### ISSUE THREAD

**Issue by JorgeAnzola** [Tommatheussen/Home-Assistant-Configuration#39]
Hello! I have a similar setup to yours, I just accepted the fact that I can't edit automation as they are not in the automations.yaml but I never dug it about it. You also can't edit them? Or there's a workaround? 
Thanks!

**Comment by Tommatheussen** [comment]
Lately what I've been doing is split up the automations like so:
```
automation: !include ../automations.yaml
automation split: !include_dir_merge_list ../automations
```
this allows me to have automations in YAML (for the ones that are more complex) in the automations directory. And it'll load the automations.yaml file to create and edit the automations in that one via the UI.

**Comment by JorgeAnzola** [comment]
That's awesome! Thanks for sharing that
